#!/usr/bin/env bash

set -euo pipefail

for device in $(upower -e); do
  info=$(upower -i "${device}")

  if [[ "${info}" != *"  mouse"* ]]; then
    continue
  fi

  percentage=$(echo "${info}" | awk '/percentage:/ { print $2 }')

  if [[ -n "${percentage}" ]]; then
    echo "${percentage}"
    exit
  fi
done
