install: link

link:
	ln -sfnv $(shell pwd)/zshrc $(HOME)/.zshrc
	ln -sfnv $(shell pwd)/zshenv $(HOME)/.zshenv
	ln -sfnv $(shell pwd)/zlogin $(HOME)/.zlogin
	ln -sfnv $(shell pwd)/aliases $(HOME)/.aliases

.PHONY: install link
