click_to_close = true
close_when_open = true
force_keyboard_focus = true
fullscreen = false
ignore_mouse = false
selection_wrap = true

[align]
width = 600

[align.anchors]
vertical = "center"
horizontal = "center"

[list]
height = 400
always_show = true

[search]
delay = 0

[[modules]]
name = "applications"
prefix = ""

[[modules]]
name = "commands"
prefix = ":"

[[modules]]
name = "runner"
prefix = ">"
