install: link

link:
	ln -sfnv $(shell pwd)/config $(HOME)/.gitconfig
	ln -sfnv $(shell pwd)/attributes $(HOME)/.config/git/attributes
	ln -sfnv $(shell pwd)/ignore $(HOME)/.config/git/ignore

.PHONY: install link
